# vim: set sw=4 et:
#

language: python
python:
    - "2.7"
    - "3.2"
    - "3.3"
before_install:
    - sudo apt-get update
    - sudo apt-get -y install python-gdbm python3-gdbm
install: python setup.py install
script: python setup.py test

