# http://docs.travis-ci.com/user/migrating-from-legacy/
sudo: false

language: python

python:
    - 3.5
    - 3.4
    - 2.7
    - nightly
    - pypy
    - pypy3

addons:
    apt:
        packages:
            - python-gdbm
            - python3-gdbm

before_script:
    - pip install . pytest requests

script: py.test -v -s tests

